import Head from 'next/head';
import { ArtistInput } from 'src/components/ArtistInput/ArtistInput';
import { getPlaylist } from 'src/lib/spotify';

export default function Home(props: { playlists: any }) {
	const { playlists } = props;

	return (
		<div className="container">
			<Head>
				<title>Musical Artist Lookup</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="main">
				<h1 className="title">Artist Lookup</h1>
				<p className="center">Try it, just search for an artist below.</p>

				<ArtistInput>
					<div className="container"></div>
				</ArtistInput>

				<h3>User Playlists</h3>
				{playlists.map((items: { name: string }) => (
					<li>{items.name}</li>
				))}
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const userPlaylists = await getPlaylist().then((response) => response.json());

	return {
		props: { playlists: userPlaylists.items },
	};
}

