import Head from 'next/head';
import { ArtistInput } from 'src/components/ArtistInput/ArtistInput';

export default function Home() {
	return (
		<div className="container">
			<Head>
				<title>Musical Artist Lookup</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="main">
				<h1 className="title">Artist Lookup</h1>
				<p className="center">Try it, just search for an artist below.</p>

				<ArtistInput>
					<div className="container"></div>
				</ArtistInput>
			</main>
		</div>
	);
}

